function obj = loadobj(S)

if isinteger(S)
   S = getArrayFromByteStream(S);
   obj = S;
   return;
end

if checkVersion(S.version,'0.4.0')
   obj = EventProcess(...
      'info',S.info,...
      'times',S.times_,...
      'events',S.values_,...
      'labels',S.labels,...
      'quality',S.quality,...
      'window',S.window_,... % set using original window since window_ is set internally
      'offset',S.offset_,... % set using original offset since window_ is set internally
      'tStart',S.tStart,...
      'tEnd',S.tEnd,...
      'lazyLoad',S.lazyLoad...
      );
   % Now set current window/offset
   set(obj,'window',S.window);
   set(obj,'offset',S.offset);
   % Clear queue as fresh from constructor
%   clearQueue(obj);
%   % And set queue and eval status
%   set(obj,'deferredEval',S.deferredEval);
%   set(obj,'queue',S.queue);
%   % Rerun queue if needed
%   revalOnDemand(obj);
else
   %< v 0.4.0
   obj = EventProcess(...
      'tStart',S.tStart,...
      'tEnd',S.tEnd,...
      'info',S.info,...
      'times',S.times_,...
      'events',S.values_,...
      'offset',S.offset_,...
      'window',S.window_,...
      'labels',S.labels,...
      'quality',S.quality);
   obj.window = S.window;
   obj.offset = S.offset;
end