function obj = loadobj(S)

if checkVersion(S.version,'0.4.0')
   obj = SpectralProcess(...
      'info',S.info,...
      'f',S.f,...
      'values',S.values_{1},...
      'labels',S.labels,...
      'quality',S.quality,...
      'params',S.params,...
      'tBlock',S.tBlock,...
      'tStep',S.tStep,...
      'labels',S.labels,...
      'window',S.window_,... % set using original window since window_ is set internally
      'offset',S.offset_,... % set using original offset since window_ is set internally
      'tStart',S.tStart,...
      'tEnd',S.tEnd...
      );
   % Now set current window/offset
   set(obj,'window',S.window);
   set(obj,'offset',S.offset);
   % Clear queue as fresh from constructor
   clearQueue(obj);
   % And set queue and eval status
   set(obj,'deferredEval',S.deferredEval);
   set(obj,'queue',S.queue);
   % Rerun queue if needed
   revalOnDemand(obj);
end